#!/bin/bash
yum update -y '#update the service'
yum install httpd24 <- [or future version] -> php56 git -y '#Install the current version of httpd and php'
service httpd start 
chkconfig httpd on
cd /var/www/html
